histograms:
  "res.*":
    nbins: 100
    min: -0.1
    max: 0.1

  "pull.*":
    nbins: 50
    min: -6
    max: 6

  "cov.*":
    nbins: 100
    min: -0.0005
    max: 0.0005

  # fixed mu=50
  "^n.*$":
    nbins: 50
    min: 0
    max: 51

  "truthX|truthY|recoX|recoY":
    nbins: 100
    min: -0.06
    max: 0.06

  "truthZ|recoZ":
    nbins: 100
    min: -200
    max: 200

  "truthT|recoT":
    nbins: 100
    min: -2000
    max: 2000

extra_histograms:
  - expression: df["nRecoVtx"] / df["nTrueVtx"]
    name: "recoOverTrue"
    nbins: 50
    min: 0.0
    max: 1.0
  - expression: df["nRecoVtx"] / df["nVtxDetectorAcceptance"]
    name: "recoOverAcc"
    nbins: 50
    min: 0.0
    max: 1.0
  - expression: df["nRecoVtx"] / df["nVtxReconstructable"]
    name: "recoOverRecble"
    nbins: 50
    min: 0.0
    max: 1.0
